In [76]:
import numpy as np
m1=np.matrix([[.97,0.02,0.01],[0.6,0.3,0.1],[0.2,0.1,0.7]])
m1

matrix([[0.97, 0.02, 0.01],
        [0.6 , 0.3 , 0.1 ],
        [0.2 , 0.1 , 0.7 ]])

In [77]:
m_aux=np.matrix([[],[],[]])
m_aux_anterior=np.matrix([[],[],[]])


In [78]:
for i in range(100):
    if i==0:
        m_aux=np.dot(m1,m1)
        m_aux=np.round(m_aux,4)
        print(m_aux)
        print("1-----------------------",i+2)
    else:
        y=i+1
        m_aux_anterior=m_aux
        m_aux=np.dot(m_aux,m1)
        m_aux=np.round(m_aux,4)
        if np.all(m_aux==m_aux_anterior):
            print("Matriz anterior y la nueva son iguales:")
            print("**** numero de matriz estable:" +str(y)+"****")
            print(m_aux)
            print("N-----------------------",y+1)
            break
        print(m_aux )
        print("N-----------------------",y+1)


[[0.955 0.026 0.019]
 [0.782 0.112 0.106]
 [0.394 0.104 0.502]]
1----------------------- 2
[[0.946 0.029 0.025]
 [0.847 0.06  0.093]
 [0.545 0.089 0.366]]
N----------------------- 3
[[0.94  0.03  0.03 ]
 [0.876 0.044 0.08 ]
 [0.655 0.074 0.271]]
N----------------------- 4
[[0.936 0.031 0.033]
 [0.892 0.039 0.069]
 [0.734 0.062 0.204]]
N----------------------- 5
[[0.933 0.031 0.036]
 [0.902 0.036 0.061]
 [0.79  0.054 0.156]]
N----------------------- 6
[[0.931 0.032 0.038]
 [0.909 0.035 0.055]
 [0.83  0.048 0.122]]
N----------------------- 7
[[0.93  0.032 0.039]
 [0.914 0.034 0.051]
 [0.858 0.043 0.098]]
N----------------------- 8
[[0.929 0.032 0.04 ]
 [0.917 0.034 0.048]
 [0.878 0.04  0.081]]
N----------------------- 9
[[0.928 0.032 0.04 ]
 [0.919 0.033 0.046]
 [0.892 0.038 0.069]]
N----------------------- 10
[[0.927 0.032 0.04 ]
 [0.92  0.033 0.045]
 [0.902 0.036 0.061]]
N----------------------- 11
[[0.926 0.032 0.04 ]
 [0.921 0.033 0.044]
 [0.909 0.035 0.055]]
N-----------------------

In [79]:
#calcuar el prosentaje de poblacion
poblacion_inicial=np.matrix([100,0,0])
poblacion_inicial

matrix([[100,   0,   0]])

In [80]:
print("Poblacion inicial -------------v0")

for z in range(20):
    if z==0:
        poblacion_inicial=np.dot(poblacion_inicial,m1)
        poblacion_inicial=np.round(poblacion_inicial,2)
        print(poblacion_inicial)
        print("Poblacion inicial ")
        print("-----------------------",z+1)
    else:
        poblacion_anterior=poblacion_inicial
        poblacion_inicial=np.dot(poblacion_inicial,m1)
        poblacion_inicial=np.round(poblacion_inicial,2)
        if np.all(poblacion_inicial==poblacion_anterior):
            print("Poblacion anterior y la nueva son iguales:")
            print("**** numero de poblacion estable:" +str(z)+"****")
            poblacion_inicial=np.round(poblacion_inicial,0)
            poblacion_inicial=poblacion_inicial.astype(int)
          
            print("poblacion Final",poblacion_inicial)
            print("N-----------------------",z+1)
            break
        print(poblacion_inicial)
        print("poblacion iteracion",z+1)

        


Poblacion inicial -------------v0
[[97.  2.  1.]]
Poblacion inicial 
----------------------- 1
[[95.49  2.64  1.87]]
poblacion iteracion 2
[[94.58  2.89  2.53]]
poblacion iteracion 3
[[93.98  3.01  3.01]]
poblacion iteracion 4
[[93.57  3.08  3.35]]
poblacion iteracion 5
[[93.28  3.13  3.59]]
poblacion iteracion 6
[[93.08  3.16  3.76]]
poblacion iteracion 7
[[92.94  3.19  3.88]]
poblacion iteracion 8
[[92.84  3.2   3.96]]
poblacion iteracion 9
[[92.77  3.21  4.02]]
poblacion iteracion 10
[[92.72  3.22  4.06]]
poblacion iteracion 11
[[92.68  3.23  4.09]]
poblacion iteracion 12
[[92.66  3.23  4.11]]
poblacion iteracion 13
[[92.64  3.23  4.13]]
poblacion iteracion 14
[[92.62  3.23  4.14]]
poblacion iteracion 15
[[92.61  3.24  4.15]]
poblacion iteracion 16
[[92.61  3.24  4.16]]
poblacion iteracion 17
Poblacion anterior y la nueva son iguales:
**** numero de poblacion estable:17****
poblacion Final [[93  3  4]]
N----------------------- 18


In [82]:
autos=100
autos_en_taller=round(autos*(m_aux[2,1]+m_aux[2,2]),0)
autos_en_taller

np.float64(7.0)

In [85]:
utilidad=50
rep_men=100
rep_may=150

utilidad_en_taller=(utilidad*(m_aux[2,0])) -(rep_men*(m_aux[2,1]))-(rep_may*(m_aux[2,2]))
print("Utilidad promedio en el taller",utilidad_en_taller)
print("utilidad anual:",utilidad_en_taller*365)

Utilidad promedio en el taller 36.80000000000001
utilidad anual: 13432.000000000004
